# SELECT
#     T1.ID AS `1ST_GEN_ID`, T1.PARENT_ID AS `1ST_GEN_PARENT_ID`
# ,   T2.ID AS `2ND_GEN_ID`, T2.PARENT_ID AS `2ND_GEN_PARENT_ID`
# ,   T3.ID AS `3RD_GEN_ID`, T3.PARENT_ID AS `3RD_GEN_PARENT_ID`
# ,   T4.ID AS `4TH_GEN_ID`, T4.PARENT_ID AS `4TH_GEN_PARENT_ID`
# FROM
#     ECOLI_DATA AS T1
# INNER JOIN
#     ECOLI_DATA AS T2
# ON
#     T1.ID = T2.PARENT_ID
# AND T1.PARENT_ID IS NULL
# LEFT JOIN
#     ECOLI_DATA AS T3
# ON
#     T2.ID = T3.PARENT_ID
# LEFT JOIN
#     ECOLI_DATA AS T4
# ON
#     T3.ID = T4.PARENT_ID;


SELECT
    T3.ID
FROM
    ECOLI_DATA AS T1
INNER JOIN
    ECOLI_DATA AS T2
ON
    T1.ID = T2.PARENT_ID
AND T1.PARENT_ID IS NULL
INNER JOIN
    ECOLI_DATA AS T3
ON
    T2.ID = T3.PARENT_ID
ORDER BY 1;