WITH CTE AS (
    SELECT
        LOCATION2
    ,   YEAR(YM) AS "YEAR"
    ,   PM_VAL1
    ,   PM_VAL2
    FROM
        AIR_POLLUTION
    WHERE
        LOCATION2 = '수원'
)
SELECT
    YEAR
,   ROUND(AVG(PM_VAL1), 2) AS "PM10"
,   ROUND(AVG(PM_VAL2), 2) AS "PM2.5"
FROM
    CTE
GROUP BY YEAR
ORDER BY 1 ASC;