# SELECT
#     *
# FROM
#     CAR_RENTAL_COMPANY_CAR AS C
# INNER JOIN
#     CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
# ON
#     C.CAR_ID = H.CAR_ID
# LEFT JOIN
#     CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
# ON
#     C.CAR_TYPE = P.CAR_TYPE
# AND P.DURATION_TYPE = (
#     CASE
#         WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
#         WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
#         WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >=  7 THEN  '7일 이상'
#         ELSE NULL
#     END
# )
# WHERE
#     C.CAR_TYPE IN ('세단', 'SUV')
# AND
#     (H.END_DATE < '2022-11-01' AND H.START_DATE < '2022-11-01')
# ORDER BY C.CAR_ID, H.END_DATE


SELECT
    T.CAR_ID
,   T.CAR_TYPE
,   ROUND(T.DAILY_FEE * 30 * (1.0 - P.DISCOUNT_RATE / 100)) AS FEE
FROM (
    SELECT DISTINCT
        C.CAR_ID
    ,   C.CAR_TYPE
    ,   C.DAILY_FEE
    ,   '30일 이상' AS DURATION_TYPE
    FROM
        CAR_RENTAL_COMPANY_CAR AS C
    INNER JOIN
        CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    ON
        C.CAR_ID = H.CAR_ID
    WHERE
        C.CAR_TYPE IN ('세단', 'SUV')
    AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H2
        WHERE
            H2.CAR_ID = C.CAR_ID
            AND H2.START_DATE <= '2022-11-30'
            AND H2.END_DATE   >= '2022-11-01'
    )
) AS T
INNER JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON
    T.CAR_TYPE = P.CAR_TYPE AND T.DURATION_TYPE = P.DURATION_TYPE
WHERE
    ROUND(T.DAILY_FEE * 30 * (1.0 - P.DISCOUNT_RATE / 100)) >= 500000
AND ROUND(T.DAILY_FEE * 30 * (1.0 - P.DISCOUNT_RATE / 100)) <  2000000
ORDER BY
    FEE DESC, T.CAR_TYPE ASC, T.CAR_ID DESC;