/*
SELECT
    FOOD_TYPE
,   REST_ID
,   REST_NAME
,   MAX(FAVORITES) AS `FAVORITES`
FROM
    REST_INFO
GROUP BY
    FOOD_TYPE
ORDER BY
    FOOD_TYPE DESC;
*/
/*
SELECT
    FOOD_TYPE
,   REST_ID
,   REST_NAME
,   FAVORITES
,   DENSE_RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) `DENSE_RANK`
FROM
    REST_INFO
ORDER BY
    FOOD_TYPE DESC
*/
SELECT
    FOOD_TYPE
,   REST_ID
,   REST_NAME
,   FAVORITES
FROM (
    SELECT
        FOOD_TYPE
    ,   REST_ID
    ,   REST_NAME
    ,   FAVORITES
    ,   DENSE_RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS `FT-FAV_DENSE_RANK`
    FROM
        REST_INFO
) AS R
WHERE 1=1
AND `FT-FAV_DENSE_RANK` = 1
ORDER BY
    FOOD_TYPE DESC;


