SELECT
    B.WRITER_ID AS `USER_ID`
,   U.NICKNAME
,   CONCAT_WS(' ', U.CITY, U.STREET_ADDRESS1, U.STREET_ADDRESS2) AS `전체주소`
,   CONCAT_WS('-', LEFT(TLNO, 3), IF(LENGTH(TLNO) < 11, MID(TLNO, 4, 3), MID(TLNO, 4, 4)), RIGHT(TLNO, 4)) AS `전화번호`
FROM
    USED_GOODS_BOARD AS B
INNER JOIN
    USED_GOODS_USER  AS U
ON
    B.WRITER_ID = U.USER_ID
GROUP BY
    B.WRITER_ID
HAVING
    COUNT(B.WRITER_ID) >= 3
ORDER BY
    `USER_ID` DESC;
