# SELECT
#     *
# FROM
#     APPOINTMENT
# WHERE 1=1
# AND MCDP_CD = 'CS'
# AND APNT_CNCL_YN = 'N'
# AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'


# SELECT
#     APNT_NO
# ,   PT_NO
# ,   MCDP_CD
# ,   MDDR_ID
# ,   APNT_YMD
# FROM
#     APPOINTMENT
# WHERE 1=1
# AND MCDP_CD = 'CS'
# AND APNT_CNCL_YN = 'N'
# AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'

SELECT
    A.APNT_NO
,   P.PT_NAME
,   P.PT_NO
,   A.MCDP_CD
,   D.DR_NAME
,   A.APNT_YMD
FROM 
    APPOINTMENT AS A
INNER JOIN
    DOCTOR AS D
ON
    A.MDDR_ID = D.DR_ID
INNER JOIN
    PATIENT AS P
ON
    A.PT_NO = P.PT_NO
WHERE 1=1
AND A.MCDP_CD = 'CS'
AND A.APNT_CNCL_YN = 'N'
AND DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
ORDER BY
    APNT_YMD ASC;