SELECT
    U.USER_ID
,   U.NICKNAME
,   SUM(B.PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD AS B
INNER JOIN
    USED_GOODS_USER  AS U
ON
    B.WRITER_ID = U.USER_ID
WHERE 1=1
AND B.`STATUS` = 'DONE'
GROUP BY
    U.USER_ID, U.NICKNAME
HAVING SUM(B.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;