WITH CTE_REST_REVIEW AS (
    SELECT
        *
    ,   COUNT(*) OVER (PARTITION BY MEMBER_ID) AS REVIEW_CNT
    FROM
        REST_REVIEW
)
SELECT
    M.MEMBER_NAME
,   R.REVIEW_TEXT
,   DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    CTE_REST_REVIEW AS R
INNER JOIN
    MEMBER_PROFILE AS M
ON
    R.MEMBER_ID = M.MEMBER_ID
WHERE
    R.REVIEW_CNT = (
        SELECT
            MAX(REVIEW_CNT)
        FROM
            CTE_REST_REVIEW
    )
ORDER BY
    R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;