# SELECT
#     CAR_ID
# ,   COUNT(*) AS CNT
# FROM
#     CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE 1=1
# AND START_DATE >= '2022-08-01'
# AND START_DATE <  '2022-11-01'
# GROUP BY CAR_ID
# HAVING COUNT(*) >= 5

/*
SELECT
    MONTH(START_DATE) AS `MONTH`
,   CAR_ID
,   COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T1
WHERE EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T2
    WHERE 1=1
    AND START_DATE >= '2022-08-01'
    AND START_DATE <  '2022-11-01'
    AND T1.CAR_ID = T2.CAR_ID
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
GROUP BY `MONTH`, CAR_ID
ORDER BY 1, 2 DESC;
*/

# SELECT
#     MONTH(START_DATE) AS `MONTH`
# ,   CAR_ID
# ,   COUNT(*) AS RECORDS
# FROM
#     CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE 1=1
# AND START_DATE >= '2022-08-01'
# AND START_DATE <  '2022-11-01'
# GROUP BY CAR_ID, MONTH(START_DATE)
# HAVING COUNT(*) >= 5
# ORDER BY 1, 2 DESC;

SELECT
    `MONTH`
,   CAR_ID
,   COUNT(*) AS RECORDS
FROM (
    SELECT
        MONTH(START_DATE) AS `MONTH`
    ,   CAR_ID
    ,   COUNT(*) OVER (PARTITION BY CAR_ID) AS PERIOD_RENTAL_CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
) AS CRH
WHERE
    PERIOD_RENTAL_CNT >= 5
GROUP BY
    `MONTH`, CAR_ID
ORDER BY 1, 2 DESC;
