SELECT
    PROD_CODE_PREFIX AS CATEGORY
,   COUNT(*)         AS PRODUCTS
FROM (
    SELECT
        SUBSTRING(PRODUCT_CODE, 1, 2) AS PROD_CODE_PREFIX
    FROM
        PRODUCT
) AS CATEGORY
GROUP BY
    PROD_CODE_PREFIX
ORDER BY
    PROD_CODE_PREFIX ASC;