SELECT
    E1.DIFFERENTIATION_YEAR                         AS 'YEAR'
,   E2.SIZE_OF_COLONY_YEAR_MAX - E1.SIZE_OF_COLONY  AS 'YEAR_DEV'
,   E1.ID
FROM (
    SELECT
        ID
    ,   SIZE_OF_COLONY
    ,   YEAR(DIFFERENTIATION_DATE) AS 'DIFFERENTIATION_YEAR'
    FROM
        ECOLI_DATA
) AS E1
INNER JOIN (
    SELECT
        MAX(SIZE_OF_COLONY)        AS 'SIZE_OF_COLONY_YEAR_MAX'
    ,   YEAR(DIFFERENTIATION_DATE) AS 'DIFFERENTIATION_YEAR'
    FROM
        ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS E2
ON
    E1.DIFFERENTIATION_YEAR = E2.DIFFERENTIATION_YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;
    

