SELECT
    H.CAR_ID
# ,   C.CAR_TYPE
# ,   H.START_DATE
# ,   H.END_DATE
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
INNER JOIN
    CAR_RENTAL_COMPANY_CAR AS C
ON
    H.CAR_ID = C.CAR_ID
WHERE 1=1
AND CAR_TYPE = '세단'
AND MONTH(START_DATE) = 10
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;