# /*
WITH FISH_AGGR AS (
    SELECT
        I.ID
    ,   I.FISH_TYPE
    ,   I.LENGTH
    ,   N.FISH_NAME
    ,   MAX(I.LENGTH) OVER (PARTITION BY I.FISH_TYPE) AS MAX_LEN_FISH_TYPE
    ,   DENSE_RANK() OVER (PARTITION BY I.FISH_TYPE ORDER BY I.LENGTH DESC) AS LEN_RANK
    FROM
        FISH_INFO AS I
    INNER JOIN
        FISH_NAME_INFO AS N
    ON
        I.FISH_TYPE = N.FISH_TYPE
)
SELECT
    ID
,   FISH_NAME
,   LENGTH
FROM
    FISH_AGGR
WHERE
    LEN_RANK = 1
ORDER BY ID;
# */
/*
SELECT
    ID
,   FISH_NAME
,   LENGTH
FROM (
    SELECT
        I.ID
    ,   I.FISH_TYPE
    ,   I.LENGTH
    ,   N.FISH_NAME
    ,   DENSE_RANK() OVER (PARTITION BY I.FISH_TYPE ORDER BY I.LENGTH DESC) AS LEN_RANK
    FROM
        FISH_INFO AS I
    INNER JOIN
        FISH_NAME_INFO AS N
    ON
        I.FISH_TYPE = N.FISH_TYPE
) AS FISH_AGGR
WHERE
    LEN_RANK = 1
ORDER BY ID;
*/
/*
SELECT
    I.ID
,   N.FISH_NAME
,   I.LENGTH
FROM
    FISH_INFO AS I
INNER JOIN
    FISH_NAME_INFO AS N
ON
    I.FISH_TYPE = N.FISH_TYPE
WHERE I.LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO AS I2
    WHERE I.FISH_TYPE = I2.FISH_TYPE
)
ORDER BY ID;
*/