# SELECT
#     *
# FROM
#     USED_GOODS_BOARD AS B
# INNER JOIN
#     USED_GOODS_FILE  AS F
# ON
#     B.BOARD_ID = F.BOARD_ID

WITH MAX_VIEWS AS (
    SELECT
        BOARD_ID
    FROM
        USED_GOODS_BOARD
    ORDER BY `VIEWS` DESC
    LIMIT 1
)
SELECT
    CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM
    USED_GOODS_FILE AS F
WHERE EXISTS (
    SELECT
        BOARD_ID
    FROM
        MAX_VIEWS AS M
    WHERE
        F.BOARD_ID = M.BOARD_ID
)
ORDER BY FILE_ID DESC;
