/*
SELECT
    B.BOOK_ID
,   B.CATEGORY
# ,   B.AUTHOR_ID
,   B.PRICE
# ,   B.PUBLISHED_DATE
,   S.SALES_DATE
,   S.SALES
FROM
    BOOK AS B
INNER JOIN
    BOOK_SALES AS S
ON
    B.BOOK_ID = S.BOOK_ID
ORDER BY B.BOOK_ID, B.CATEGORY, S.SALES_DATE;
*/
/*
SELECT
    B.CATEGORY
,   SUM(S.SALES) OVER (PARTITION BY B.CATEGORY)
FROM
    BOOK AS B
INNER JOIN
    BOOK_SALES AS S
ON
    B.BOOK_ID = S.BOOK_ID
ORDER BY B.CATEGORY ASC;
*/
SELECT
    B.CATEGORY
,   SUM(S.SALES) AS TOTAL_SALES
FROM
    BOOK AS B
INNER JOIN
    BOOK_SALES AS S
ON
    B.BOOK_ID = S.BOOK_ID
WHERE 1=1
    # DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
AND SALES_DATE >= '2022-01-01'
AND SALES_DATE <  '2022-02-01'
GROUP BY
    B.CATEGORY
ORDER BY B.CATEGORY ASC;

