# SELECT
#     *
# ,   DENSE_RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS PRICE_RANK
# ,   MAX(PRICE) OVER (PARTITION BY CATEGORY) AS MAX_PRICE
# FROM
#     FOOD_PRODUCT
# WHERE
#     CATEGORY IN ('과자', '국', '김치', '식용유');


WITH CTE_FR AS (
    SELECT
        *
    # ,   DENSE_RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS PRICE_RANK
    ,   MAX(PRICE) OVER (PARTITION BY CATEGORY) AS MAX_PRICE
    FROM
        FOOD_PRODUCT
    WHERE
        CATEGORY IN ('과자', '국', '김치', '식용유')
)
SELECT
    CATEGORY
,   MAX_PRICE
,   PRODUCT_NAME
FROM
    CTE_FR
WHERE 1=1
# AND PRICE_RANK = 1
AND PRICE = MAX_PRICE
ORDER BY
    MAX_PRICE DESC;



