WITH CTE_PROD AS (
    SELECT
        (TRUNCATE(PRICE / 10000, 0) * 10000) AS PRICE_GROUP
    FROM
        PRODUCT
)
SELECT
    PRICE_GROUP
,   COUNT(*)
FROM
    CTE_PROD
GROUP BY
    PRICE_GROUP
ORDER BY
    PRICE_GROUP ASC;